---
sudo: required
language: python

services:
  - docker

python: "2.7"

virtualenv:
  system_site_packages: false

install:
- pip install --upgrade setuptools
- pip install .

script:
- ansible-galaxy install openmicroscopy.$ROLE --roles-path . --no-deps
# molecule test playbooks expect the directory to match the repository name
- mv openmicroscopy.$ROLE ansible-role-$ROLE
- cd ansible-role-$ROLE
# Some roles can't be properly tested in Docker
# These should provide an alternative configuration just for testing syntax
- if [ -f molecule-docker.yml ]; then mv molecule-docker.yml molecule.yml; fi
- ../test.sh

### GENERATED ###
env:
- ROLE=basedeps
- ROLE=cadvisor
- ROLE=celery-docker
- ROLE=docker
- ROLE=docker-tools
- ROLE=haproxy
# Syntax only
- ROLE=hosts-populate
- ROLE=ice
- ROLE=java
- ROLE=jekyll-build
- ROLE=local-accounts
- ROLE=logrotate
- ROLE=lvm-partition
- ROLE=munin
- ROLE=munin-node
- ROLE=mysql-backup
- ROLE=network-cloud-interfaces
- ROLE=nfs-mount
# Syntax only
- ROLE=nfs-share
- ROLE=nginx
- ROLE=nginx-proxy
- ROLE=nginx-ssl-selfsigned
- ROLE=omego
- ROLE=omero-logmonitor
- ROLE=omero-python-deps
- ROLE=omero-server
- ROLE=omero-user
- ROLE=omero-web
- ROLE=omero-web-apps
- ROLE=omero-web-runtime
- ROLE=openstack-volume-storage
- ROLE=postgresql
- ROLE=python-pydata
- ROLE=reboot-server
- ROLE=redis
- ROLE=rsync-server
- ROLE=samba-client
- ROLE=selinux-utils
- ROLE=storage-volume-initialise
- ROLE=sudoers
- ROLE=system-monitor-agent
- ROLE=upgrade-distpackages
- ROLE=versioncontrol-utils
### GENERATED ###

### molecule syntax check only

matrix:
  allow_failures:
  # Uses a non-standard test from upstream
  - env: ROLE=haproxy
  # No molecule.yml or test.yml (tested by munin role)
  - env: ROLE=munin-node
  # Molecule test doesn't work
  - env: ROLE=omero-logmonitor
  # Broken (deprecated?)
  - env: ROLE=omero-web-apps
